// The packaged clients and the web build must not depend on an external font host: a mainland-reachable player or an
// offline LAN session used to hang on fonts.googleapis.com / stall on a blocked gstatic. The mirror is generated by
// tools/fetch-webfonts.mjs from the very files Google serves (same unicode-range slices, same display=swap), so the
// only thing these assertions can break is a future edit that reintroduces a remote reference or drops a slice.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { nameFor } from '../tools/fetch-webfonts.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIR = path.join(ROOT, 'public', 'webfonts', 'google');
const REMOTE = /fonts\.(googleapis|gstatic)\.com/g;

const html = await readFile(path.join(ROOT, 'public', 'index.html'), 'utf8');
const sheet = await readFile(path.join(DIR, 'google.css'), 'utf8');
const files = (await readdir(DIR)).filter((f) => f.endsWith('.woff2'));

test('index.html carries no external font host and links the local sheet', () => {
  assert.equal(REMOTE.test(html), false, 'index.html 又出现远程字体地址');
  REMOTE.lastIndex = 0;
  assert.equal((html.match(/href="\/webfonts\/google\/google\.css"/g) || []).length, 1, '本地样式表恰好引用一次');
  assert.match(html, /media="print" onload="this\.media='all'" href="\/webfonts\/google\/google\.css"/,
    '仍按不阻塞渲染的方式加载（离线/局域网开局不受字体影响）');
});

test('the generated sheet resolves every url() locally, and nothing remotely', async () => {
  assert.equal(REMOTE.test(sheet), false, '生成物里残留远程地址');
  REMOTE.lastIndex = 0;
  const urls = [...new Set(sheet.match(/url\(\/webfonts\/google\/[^)]+\.woff2\)/g) || [])];
  assert.ok(urls.length > 100, `切片数量不对（只找到 ${urls.length}）`);
  const names = urls.map((u) => /^url\(\/webfonts\/google\/(.+)\)$/.exec(u)[1]);
  assert.equal(new Set(names).size, names.length, 'url 指向重名文件');
  for (const n of names.slice(0, 12)) {
    const p = path.join(DIR, n);
    assert.ok((await stat(p)).isFile(), `缺文件 ${n}`);
  }
  assert.deepEqual(names.filter((n) => !files.includes(n)), [], '有 url() 指向不存在的文件');
});

test('every mirrored slice is a real woff2 and matches the generator naming', async () => {
  for (const n of files) {
    const buf = await readFile(path.join(DIR, n));
    assert.equal(buf.subarray(0, 4).toString('latin1'), 'wOF2', `${n} 不是 woff2`);
    assert.ok(buf.length > 200, `${n} 太小`);
  }
  // The name is derived from the URL, so re-deriving it from a synthetic URL must land on a file we ship.
  const sample = 'https://fonts.gstatic.com/s/notosanssc/v41/abcdefgh.69.woff2';
  assert.match(nameFor(sample), /^notosanssc-v41-abcdefgh\.69-[0-9a-f]{8}\.woff2$/);
});

test('the families the game asks Google for are all covered locally', () => {
  const families = [...new Set([...sheet.matchAll(/font-family: '([^']+)'/g)].map((m) => m[1]))];
  for (const want of ['Noto Sans SC', 'Rajdhani', 'Oxanium']) assert.ok(families.includes(want), `缺 ${want}`);
  const weights = new Set([...sheet.matchAll(/font-weight: ([\d ]+);/g)].map((m) => m[1].trim()));
  for (const w of ['400', '500', '700', '900']) assert.ok(weights.has(w), `缺字重 ${w}`);
  assert.equal(sheet.match(/font-display: swap/g)?.length > 100, true, 'swap 时序未保留');
});

/**
 * The whole shipped tree, not just index.html: dev/uikit.html used to keep its own css2 link, and a page that
 * reaches a font host is exactly what breaks a LAN/offline session. Text sources only — binary assets are scanned
 * by the payload gate in the client repo.
 */
test('no file under public/ references an external font host', async () => {
  const exts = new Set(['.html', '.css', '.js', '.mjs', '.json']);
  const hits = [];
  const walk = async (dir) => {
    for (const e of await readdir(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) { await walk(p); continue; }
      if (!exts.has(path.extname(e.name))) continue;
      const text = await readFile(p, 'utf8');
      if (/fonts\.(googleapis|gstatic)\.com/.test(text)) hits.push(path.relative(ROOT, p));
    }
  };
  await walk(path.join(ROOT, 'public'));
  assert.deepEqual(hits, [], `这些文件还引用外部字体主机：${hits.join(', ')}`);
});

/**
 * 离线/局域网必须零外呼 —— 与客户端仓库 tools/check-payload-offline.mjs 同一套判据：只看**引用形式**，
 * 不看裸 URL。public/ 里本来就有上百条裸 URL（three.js/pixi 注释里的文档与许可证地址、SVG 的 xmlns 标识符），
 * 它们不发请求；把它们一起禁掉只会让闸门三天内被静音。所以下面既断言"引用形式为 0"，也断言"裸 URL 不为 0"，
 * 后者是这条测试的自校准：哪天扫描没跑到位，它先红。
 */
test('nothing under public/ points a request at an off-device URL', async () => {
  const FORMS = [
    /(?:href|src|action|poster|data-src)\s*=\s*["'](https?:\/\/[^"'\s]+)/g,
    /url\(\s*["']?(https?:\/\/[^)'"\s]+)/g,
    /(?:fetch|import|axios\.get)\s*\(\s*["'](https?:\/\/[^'"\s]+)/g,
    /new\s+WebSocket\s*\(\s*["'`](https?:\/\/[^'"`\s)]+)/g,
    /@import\s+(?:url\()?\s*["']?(https?:\/\/[^)'"\s]+)/g,
  ];
  const BARE = /https?:\/\/[^\s"'<>)\]]+/g;
  const exts = new Set(['.html', '.css', '.js', '.mjs', '.json', '.svg', '.txt', '.atlas']);
  const hits = [];
  let bare = 0;
  const walk = async (dir) => {
    for (const e of await readdir(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) { await walk(p); continue; }
      if (!exts.has(path.extname(e.name).toLowerCase())) continue;
      const text = await readFile(p, 'utf8');
      for (const rx of FORMS) for (const m of text.matchAll(rx)) hits.push(`${path.relative(ROOT, p)} → ${m[1]}`);
      bare += [...text.matchAll(BARE)].length;
    }
  };
  await walk(path.join(ROOT, 'public'));
  assert.deepEqual(hits, [], `这些是真正会发出去的站外请求：\n  ${hits.slice(0, 8).join('\n  ')}`);
  assert.ok(bare > 20, `裸 URL 计数只有 ${bare} —— 扫描大概没跑到 vendor/，这条测试就失去意义了`);
});
