// The packaged clients and the web build must not depend on an external font host: a mainland-reachable player or an
// offline LAN session used to hang on fonts.googleapis.com / stall on a blocked gstatic. The mirror is generated by
// tools/fetch-webfonts.mjs from the very files Google serves (same unicode-range slices, same display=swap), so the
// only thing these assertions can break is a future edit that reintroduces a remote reference or drops a slice.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { nameFor } from '../tools/fetch-webfonts.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIR = path.join(ROOT, 'public', 'webfonts', 'google');
const REMOTE = /fonts\.(googleapis|gstatic)\.com/g;

const html = await readFile(path.join(ROOT, 'public', 'index.html'), 'utf8');
const sheet = await readFile(path.join(DIR, 'google.css'), 'utf8');
const files = (await readdir(DIR)).filter((f) => f.endsWith('.woff2'));

test('index.html carries no external font host and links the local sheet', () => {
  assert.equal(REMOTE.test(html), false, 'index.html 又出现远程字体地址');
  REMOTE.lastIndex = 0;
  assert.equal((html.match(/href="\/webfonts\/google\/google\.css"/g) || []).length, 1, '本地样式表恰好引用一次');
  assert.match(html, /media="print" onload="this\.media='all'" href="\/webfonts\/google\/google\.css"/,
    '仍按不阻塞渲染的方式加载（离线/局域网开局不受字体影响）');
});

test('the generated sheet resolves every url() locally, and nothing remotely', async () => {
  assert.equal(REMOTE.test(sheet), false, '生成物里残留远程地址');
  REMOTE.lastIndex = 0;
  const urls = [...new Set(sheet.match(/url\(\/webfonts\/google\/[^)]+\.woff2\)/g) || [])];
  assert.ok(urls.length > 100, `切片数量不对（只找到 ${urls.length}）`);
  const names = urls.map((u) => /^url\(\/webfonts\/google\/(.+)\)$/.exec(u)[1]);
  assert.equal(new Set(names).size, names.length, 'url 指向重名文件');
  for (const n of names.slice(0, 12)) {
    const p = path.join(DIR, n);
    assert.ok((await stat(p)).isFile(), `缺文件 ${n}`);
  }
  assert.deepEqual(names.filter((n) => !files.includes(n)), [], '有 url() 指向不存在的文件');
});

test('every mirrored slice is a real woff2 and matches the generator naming', async () => {
  for (const n of files) {
    const buf = await readFile(path.join(DIR, n));
    assert.equal(buf.subarray(0, 4).toString('latin1'), 'wOF2', `${n} 不是 woff2`);
    assert.ok(buf.length > 200, `${n} 太小`);
  }
  // The name is derived from the URL, so re-deriving it from a synthetic URL must land on a file we ship.
  const sample = 'https://fonts.gstatic.com/s/notosanssc/v41/abcdefgh.69.woff2';
  assert.match(nameFor(sample), /^notosanssc-v41-abcdefgh\.69-[0-9a-f]{8}\.woff2$/);
});

test('the families the game asks Google for are all covered locally', () => {
  const families = [...new Set([...sheet.matchAll(/font-family: '([^']+)'/g)].map((m) => m[1]))];
  for (const want of ['Noto Sans SC', 'Rajdhani', 'Oxanium']) assert.ok(families.includes(want), `缺 ${want}`);
  const weights = new Set([...sheet.matchAll(/font-weight: ([\d ]+);/g)].map((m) => m[1].trim()));
  for (const w of ['400', '500', '700', '900']) assert.ok(weights.has(w), `缺字重 ${w}`);
  assert.equal(sheet.match(/font-display: swap/g)?.length > 100, true, 'swap 时序未保留');
});
